LoadPlugin python
<Plugin python>
    ModulePath "/usr/share/collectd/nagios-perfdata"
    Import "nagios_perfdata"
    <Module nagios_perfdata>
        SpoolDirectory "/var/lib/nagios/spool/graphios"
        ReplacementChar "_"
        UseServiceDesc false
        Interval 15
    </Module>
</Plugin>
