
auditbeat.modules:

- module: auditd
  audit_rule_files: [ '${path.config}/audit.rules.d/*.conf' ]
  audit_rules: |

- module: file_integrity
  paths:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    - /etc
  recursive: true
  exclude_files:
    - '~$'
    - '\.[0-9]+$'
    - '\.tmp$'
    - '/\.'
    - '^/etc/portage/package\.'
    - '^/etc/portage/repos.conf/(rbkmoney.conf|gentoo.conf)'
    - '^/etc/salt/pki/master/minions/\.'
    - '^/etc/salt/gpgkeys/pubring.kbx.lock'
    - '^/etc/dnssec/root-anchors.txt'
    - '^/etc/openvpn/msk1-edge/ipp.txt'
    - '^/etc/salt/minion.d/_'
    - '^/etc/wallarm/\.?lom(\.new)?'
    - '^/etc/salt/master.d/roots.conf'
    - '^/etc/macroservice/'
    - '^/etc/lvm/(backup|archive)'
    # - '^/etc/postgresql-11/postgresql.conf'

{% if salt['grains.get']('security-scope','') == 'pci-dss' %}
queue.spool:
  file:
    path: "${path.data}/spool.dat"
    size: 200MiB
    page_size: 4KiB
    prealloc: false
  write:
    buffer_size: 10MiB
    flush.timeout: 5s
    flush.events: 1024
{% endif %}

setup:
  template: {enabled: false}

name: {{ grains['fqdn'] }}

setup.kibana:

output.elasticsearch:
  bulk_max_size: 500
  hosts: ['https://es-hot1.bst1.rbkmoney.net:9200/', 'https://es-hot2.bst1.rbkmoney.net:9200/',
    'https://es-hot3.bst1.rbkmoney.net:9200/', 'https://es-hot4.bst1.rbkmoney.net:9200/',
    'https://es-hot5.bst1.rbkmoney.net:9200/', 'https://es-hot6.bst1.rbkmoney.net:9200/',
    'https://es-hot7.bst1.rbkmoney.net:9200/', 'https://es-hot8.bst1.rbkmoney.net:9200/']
  index: audit-%{+yyyy.MM.dd}
  loadbalance: true
  ssl:
    enabled: true
    certificate: /etc/auditbeat/elasticsearch-cert.pem
    key: /etc/auditbeat/elasticsearch-key.pem
    certificate_authorities:
      - /etc/auditbeat/elasticsearch-ca.pem
  pipeline: auditbeat
  template: 
    enabled: false

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
